#!/bin/sh
#
# Ran after git flow feature start
#

NAME=$1
ORIGIN=$2
BRANCH=$3
BASE=$4

set_maven_version() {
  require_maven

  local branch_version=$(echo $BRANCH | tr "/" "-")

  echo "Setting version to ${branch_version}-SNAPSHOT"
  mvn versions:set -DnewVersion=${BRANCH_VERSION}-SNAPSHOT -DgenerateBackupPoms=false
  git commit -am "Setting version to ${BRANCH_VERSION}-SNAPSHOT"
}

exit 0
