#!/bin/sh
#
# Ran after git flow feature publish
#

NAME=$1
ORIGIN=$2
BRANCH=$3

BRANCH_VERSION=$(echo $BRANCH | tr "/" "-")

JENKINS_URL="http://jenkins.server.org"
JENKINS_PARAMS="/view/All/createItem?name="

if [ -f pom.xml ]
then
	# Get the artifactId from pom.xml
	ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId | grep -B 2 '\[INFO\] Reactor Summary' | sed -e '1q')
	#curl -X GET ${JENKINS_URL}/job/${ARTIFACT_ID}-master/config.xml -o ${ARTIFACT_ID}.xml

	# echo URL: ${JENKINS_URL}${JENKINS_PARAMS}${ARTIFACT_ID}-${BRANCH_VERSION}
	echo "Creating a Jenkins job for ${ARTIFACT_ID}-${BRANCH_VERSION}"
	# Create Jenkins job
	curl -X POST ${JENKINS_URL}${JENKINS_PARAMS}${ARTIFACT_ID}-${BRANCH_VERSION} --data-binary @jenkinsconfig.xml -H 'Content-Type: application/xml; charset=ISO-8859-1'
fi

exit 0
